### ISSUE TITLE
没有总是哈，就赞一个，太牛B了！！！！！！

### ISSUE THREAD

**Issue by nsdictionary** [bendytree/Objective-C-RegEx-Categories#11]
为作者的强大感到叹服

顺便问一问RXGroup是干嘛的？

you are powerfull, thank you!

by the way,i don,t understand this class RXGroup ,why need it????what can it do for us?

**Comment by bendytree** [comment]
If your regular expression contains [capture groups](http://www.regular-expressions.info/refcapture.html) (denoted by parenthesis) then `RXMatch` will contain the full matched string. It will also contain `groups` which is a list of `RXMatchGroup` - each of which contains the string for the group as well as the position.

There are some examples in the tests:
https://github.com/bendytree/Objective-C-RegEx-Categories/blob/master/TestProject/Objective-C-Regex-CategoriesTests/NSRegularExpression%2BMatches.m#L67
