### ISSUE TITLE
Same method name in different NSString category.

### ISSUE THREAD

**Issue by luohui8891** [bendytree/Objective-C-RegEx-Categories#12]
Hi

First of all your regular category is pretty cool.
This is Andy. I have imported both your regular lib and [ObjectiveSugar](https://github.com/supermarin/ObjectiveSugar) in my project via CocoaPods.
Then I found same method name in the two different NSString categories.
The method is `split:` . And I can't find any solution on google but I got [`Two different categories implementing the same method results in undefined behavior`](http://stackoverflow.com/questions/3221972/what-happens-if-two-objc-categories-override-the-same-method)

I know that's not anyone's bad, but do you have any suggest for me?

**Comment by bendytree** [comment]
I'm not super familiar with CocoaPods, but technically you can just remove the category in one of the repos (in the pod project). Of course, this would get clobbered if you pulled the code down again. I think the best option would be to fork one of the repos on GitHub, remove/change the category, then [reference your fork](https://github.com/CocoaPods/CocoaPods/wiki/Dependency-declaration-options) instead.

**Comment by luohui8891** [comment]
I think fork is a good idea. Thanks.
