### ISSUE TITLE
iOS7 support

### ISSUE THREAD

**Issue by hokster7** [bendytree/Objective-C-RegEx-Categories#4]
For some reason or another, the RegEx pod compiled but when I run, I get this:

``` objc
-[NSRegularExpression initWithPattern:]: unrecognized selector sent to instance 0xc2a2160
```

It looks like the actual call we want to be using here is:

``` objc
- (id)initWithPattern:(NSString *)pattern options:(NSRegularExpressionOptions)options error:(NSError **)error
```

**Comment by ben95beng** [comment]
I just installed this library using CocoaPod and I am seeing the above issue on ios 7 running on simulator. I tried this example code: 
```objective-c
BOOL isMatch = [@"I have 2 dogs." isMatch:RX(@"\\d+")];
```
and the app crashes with:

Uncaught exception: -[NSRegularExpression initWithPattern:]: unrecognized selector sent to instance 0x7ff089d472b0

Does anyone know why this happens and how to fix it?

**Comment by ben95beng** [comment]
- I found the reason. It was an issue with the pod installation. For some reason, this library was not linked properly. It was not listed under 'other linker flags' for main target. Adding it fixed the issue.

**Comment by fatuhoku** [comment]
Don't worry I've not had this issue for a while now. Thanks for your help!

**Comment by PatrickSCLin** [comment]
I occurred this situation too, was using Regex in my static library, and link my library to my swift target.

my solution is set the other link flag "-all_load" on my swift target.
