### ISSUE TITLE
Crash: groups property with copy attribute

### ISSUE THREAD

**Issue by ShingoFukuyama** [bendytree/Objective-C-RegEx-Categories#9]
Hi,

I got below error and crash with the latest version.

`Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds for empty array'`

```
NSString *string = @"View Controller";
NSString *newString = [string replace:RX(@"(View)(.*)") withDetailsBlock:^NSString *(RxMatch *match) {
    NSArray *groups = match.groups;
    return ((RxMatch *)groups[2]).value;
}];
NSLog(@"Result: %@", newString);
```

Now `groups` property is:
`@property (nonatomic, copy)     NSArray*  groups;`

When I change `copy` attribute to `strong`, the crash won't happen...
Would you check it out?

Thanks.

**Comment by ShingoFukuyama** [comment]
I have found the cause. Would you pull this? #10

**Comment by bendytree** [comment]
Thanks for the example and the fix. I merged it
